### ISSUE TITLE
Formatting option to match serde-json's default additional whitespace in mappings

### ISSUE THREAD

**Issue by jayvdb** [sigoden/jsona#48]
I am seeing a lot of diff's like the following in files which were emitted from serde
```diff
-                  { "x": 0.0, "y": 0.0 },
-                  { "x": 0.0, "y": 1.0 },
-                  { "x": 1.0, "y": 1.0 },
-                  { "x": 1.0, "y": 0.0 }
+                  {"x":0.0,"y":0.0},
+                  {"x":0.0,"y":1.0},
+                  {"x":1.0,"y":1.0},
+                  {"x":1.0,"y":0.0}
```
Would be nice if there was an option to add this whitespace for greater readability and compatibility with serde-json.

**Comment by sigoden** [comment]
Can you describe your operation process in detail?

- What's the origin file
- What's the operations (cli, or vscode format ?)
- What's the result
