### ISSUE TITLE
JSON file in VSCode formatting not working

### ISSUE THREAD

**Issue by dalisoft** [sigoden/jsona#53]
Here example of bug

https://github.com/jsona/jsona/assets/3511344/e5374ed7-c6af-49c6-a7ce-ce00f53b2710

#### VSCode config

https://github.com/dalisoft/vscode-config/blob/f2df15e9c78b202d850042d58597ac8065b321a2/settings.config.jsonc#L36-L41

#### Information

| Name | Version |
| - | - |
| `jsona-cli` | `0.6.0` |
| `jsona-vscode` | `0.4.5` |

**Comment by sigoden** [comment]
https://github.com/jsona/jsona/assets/4012553/1e34da4e-94fa-4e5c-a081-f1e3d38d55d0


https://github.com/jsona/jsona/assets/4012553/856d671f-3c82-4a99-b404-447f8b16f963

There is no problem with jsona itself. There may be a problem with vscode configuration.

**Comment by dalisoft** [comment]
Thank you for checking @sigoden 

Also, can you check please with `[json]` configuration and file with `settings.json` like in my example?

**Comment by sigoden** [comment]
https://github.com/jsona/jsona/assets/4012553/f9e49d44-702b-4608-94c7-23ff0efee8e4

**Comment by sigoden** [comment]
Use your configuration will report an error
![image](https://github.com/jsona/jsona/assets/4012553/c7497df9-e9a7-4f6d-913b-ab3100282fb4)

**Comment by sigoden** [comment]
Your issue is a vscode configuration issue, or vscode-jsona does not support the json file format. It is not a problem with jsona formatting.

**Comment by dalisoft** [comment]
Seems a `vscode-jsona` issue. But can you fix this case please?

UPD: Yes, seems `vscode-jsona` supports only `.jsona` extension

https://github.com/jsona/jsona/blob/f54db6554fd14f152e7ce8112b589eb85fa3a9c3/editors/vscode/package.json#L127-L140

**Comment by sigoden** [comment]
There are no plans to support json/jsonc in the short term.
